site_name: Various Complements
repo_url: https://github.com/tadashi-aikawa/obsidian-various-complements-plugin

theme:
  name: "material"
  icon:
    logo: material/keyboard
    repo: fontawesome/brands/github
  features:
    - navigation.sections

extra_css:
  - main.css

# Extensions
markdown_extensions:
  - footnotes
  # - attr_list
  # - pymdownx.arithmatex
  # - pymdownx.superfences
  # - pymdownx.details
  # - pymdownx.magiclink
  # - pymdownx.tasklist:
  #     custom_checkbox: true
  #  - pymdownx.emoji:
  #      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  # - admonition
  - toc:
      permalink: true

plugins:
  - search:
      lang:
        - en
      prebuild_index: true
  - roamlinks

